# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11L1DJWkcMP7yMozbzW7VTEN2b3m_NdbQ
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import seaborn as sns

# Load model
model = joblib.load("naive_bayes_model.pkl")

# Load Iris dataset
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target
df['species'] = df['target'].apply(lambda x: iris.target_names[x])

# Sidebar navigation
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to", ["Data Description", "Prediction", "About Model"])

# --- PAGE 1: Data Description ---
if page == "Data Description":
    st.title("📊 Iris Data Description")
    st.write("This is the classic Iris flower dataset.")

    st.subheader("Raw Dataset")
    st.dataframe(df.head())

    st.subheader("Class Distribution")
    st.bar_chart(df['species'].value_counts())

    st.subheader("Feature Distributions")
    fig, ax = plt.subplots()
    sns.pairplot(df, hue='species')
    st.pyplot(fig)

# --- PAGE 2: Prediction ---
elif page == "Prediction":
    st.title("🌼 Iris Flower Prediction")
    st.write("Input the features below to predict the Iris flower species.")

    # Input features
    sepal_length = st.slider("Sepal length (cm)", 4.0, 8.0, 5.0)
    sepal_width = st.slider("Sepal width (cm)", 2.0, 4.5, 3.0)
    petal_length = st.slider("Petal length (cm)", 1.0, 7.0, 4.0)
    petal_width = st.slider("Petal width (cm)", 0.1, 2.5, 1.0)

    if st.button("Predict"):
        input_data = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
        prediction = model.predict(input_data)[0]
        species_name = iris.target_names[prediction]

        st.success(f"The predicted Iris species is: **{species_name.capitalize()}**")

# --- PAGE 3: About Model ---
else:
    st.title("🤖 About the Model")
    st.markdown("""
    This app uses a **Naive Bayes** classifier trained on the Iris dataset.

    **Naive Bayes** is a probabilistic machine learning algorithm based on Bayes’ Theorem.
    It’s particularly suited for classification tasks.

    - **Features used**: Sepal & Petal dimensions
    - **Target**: Iris species (Setosa, Versicolor, Virginica)

    **Why Naive Bayes?**
    - Simple and fast
    - Works well with small datasets
    - Interpretable results

    ---
    *Built with ❤️ using Streamlit*
    """)